version: '3.8'

services:
  agent:
    build: 
      context: ./agent
      dockerfile: Dockerfile
    env_file: ./agent/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./agent:/app
    command: python -m research_canvas.demo

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    env_file: ./ui/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXT_PUBLIC_AGENT_URL=${NEXT_PUBLIC_AGENT_URL}
      - NEXT_TELEMETRY_DISABLED=${NEXT_TELEMETRY_DISABLED}
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - agent
